networks:
  microservices-net:
    name: microservices-net

services:
  service-registry:
    build: ./service-registry
    container_name: service-registry
    networks:
      - neo-banking_default
    ports:
      - "8761:8761"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761" ]
      interval: 10s
      retries: 5
      start_period: 10s

  config-server:
    build: ./config-server
    container_name: config-server
    depends_on:
      service-registry:
        condition: service_healthy
    networks:
      - neo-banking_default
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    ports:
      - "8888:8888"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      retries: 5
      start_period: 10s

  identity-service:
    build: ./identity-service
    container_name: identity-service
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - neo-banking_default
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    ports:
      - "8085:8085"
    restart: always

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - neo-banking_default
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    ports:
      - "8083:8083"
    restart: always

  account-service:
    build: ./account-service
    container_name: account-service
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - neo-banking_default
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    ports:
      - "8082:8082"
    restart: always

  customer-service:
    build: ./customer-service
    container_name: customer-service
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - neo-banking_default
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    ports:
      - "8081:8081"
    restart: always

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - neo-banking_default
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    ports:
      - "9090:9090"
    restart: always

  notification-service:
    build: ./notification-service
    container_name: notification-service
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - neo-banking_default
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    ports:
      - "8084:8084"
    restart: always