version: '3.8'

networks:
  neo_network:
    name: neo_network

services:
  service-registry:
    build: ./service-registry
    container_name: service-registry
    networks:
      - neo_network
    ports:
      - "8761:8761"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761" ]
      interval: 10s
      retries: 5
      start_period: 10s

  config-server:
    build: ./config-server
    container_name: config-server
    depends_on:
      service-registry:
        condition: service_healthy
    networks:
      - neo_network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    ports:
      - "8888:8888"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      retries: 5
      start_period: 10s

  identity-service:
    build: ./identity-service
    container_name: identity-service
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - neo_network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    ports:
      - "8085:8085"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8085/actuator/health" ]
      interval: 10s
      retries: 5
      start_period: 10s

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - neo_network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    ports:
      - "8083:8083"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 10s
      retries: 5
      start_period: 10s

  account-service:
    build: ./account-service
    container_name: account-service
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - neo_network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    ports:
      - "8082:8082"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      retries: 5
      start_period: 10s

  customer-service:
    build: ./customer-service
    container_name: customer-service
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - neo_network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    ports:
      - "8081:8081"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 5
      start_period: 10s

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - neo_network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    ports:
      - "9090:9090"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/actuator/health" ]
      interval: 10s
      retries: 5
      start_period: 10s

  notification-service:
    build: ./notification-service
    container_name: notification-service
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - neo_network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    ports:
      - "8084:8084"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8084/actuator/health" ]
      interval: 10s
      retries: 5
      start_period: 10s

  frontend:
    build: ./neo-frontend
    container_name: frontend
    networks:
      - neo_network
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_GATEWAY_URL=http://api-gateway:9090
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ]
      interval: 10s
      retries: 5
      start_period: 10s

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker
    hostname: localhost:9092
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8086:8080"
    depends_on:
      - broker
    environment:
      KAFKA_CLUSTERS_NAME: local
      KAFKA_CLUSTERS_BOOTSTRAPSERVERS: broker:29092
      DYNAMIC_CONFIG_ENABLED: 'true'
