CREATE TABLE users (
       id BIGINT AUTO_INCREMENT PRIMARY KEY,
       username VARCHAR(25) UNIQUE NOT NULL,
       email VARCHAR(50) UNIQUE NOT NULL,
       password VARCHAR(255) NOT NULL,
       roles VARCHAR(255) NOT NULL,
       status VARCHAR(20) DEFAULT 'ACTIVE',
       created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
       last_modified_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
       created_by VARCHAR(40),
       modified_by VARCHAR(40)
);