server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/iamAbode/neo-config  # Replace with your GitHub repo URL
          default-label: main
          #clone-on-start: true